### ISSUE TITLE
Uploading images to imgur account

### ISSUE THREAD

**Issue by santiyounger** [gavvvr/obsidian-imgur-plugin#5]
As we discussed with @gavvvr  in here https://github.com/gavvvr/obsidian-imgur-plugin/discussions/4#discussioncomment-590286

It'd be amazing  to be able to connect imgur uploads to ones accounts.

---
## quoted from previous conversation

> I still see the value on connecting to one's uploads to a personal imgur account

Me too. It can give you a feeling of controlling your data:
- you can see all of them at once (making sure they will not disappear because of being stale), 
- or you can remove something you pasted by accidence

So the feature request is very welcomed👍🏻. As you said, other people can find it valuable, and among them there can be a person who has enough expertise to contribute a PR

_Originally posted by @gavvvr in https://github.com/gavvvr/obsidian-imgur-plugin/discussions/4#discussioncomment-590960_

Thanks!

**Comment by gavvvr** [comment]
I just noticed that registering own `obsidian://` callback [was added to plugins API](https://github.com/obsidianmd/obsidian-api/commit/81ab85ade4552c9116c1e10d009127e62019c923#diff-0eaea5db2513fdc5fe65d534d3591db5b577fe376925187c8a624124632b7466R1809)🎉, just a month later after I released the initial version of this plugin. 
This means that I can try implementing OAuth-based login:
- with a more user-friendly imgur authentication
- more control over your images 
- and ability to choose destination imgur album for obsidian notes

**Comment by gavvvr** [comment]
At the moment I am stuck at getting token param from callback URL call. I think it is a limitation of Obsidian API for handling Obsidian protocol URLs so I described the problem in details and created my proposal here: https://forum.obsidian.md/t/parse-obsidian-protocol-url-part-after-hash/17939

Another dilemma I am thinking about: 
- Should I even open a browser to let a user authenticate at imgur.com? 
- Or I can just spawn another window within Obsidian and open imgur authentication page in it? (which should be very easy because as we know Obsidian itself is an electron/chrome-based app) 🤔 

🤔 
The 2nd option can simplify things and I can probably forget about Obsidian protocol handler limitation. But the first option is much more transparent for users: they will see exactly, that they enter their imgur credentials in their default browser with imgur.com in address bar. And for now I think it is better to go the 1st option to make things 100% transparent for user

**Comment by gavvvr** [comment]
Good news: Licat [replied](https://forum.obsidian.md/t/parse-obsidian-protocol-url-part-after-hash/17939/5) that required Obsidian Protocol handling enhancement can be implemented in the next Obsidian release

**Comment by santiyounger** [comment]
no way, man those news just made my day! Thank you so much for keeping me updated. I'm happy to help run tests on Linux and Mac if needed, looking forward

**Comment by gavvvr** [comment]
Hey @santiyounger, check out v 2.0.0. Now you can choose between Anonymous and Authenticated upload (see README.md for more info)

**Comment by santiyounger** [comment]
> Hey @santiyounger, check out v 2.0.0. Now you can choose between Anonymous and Authenticated upload (see README.md for more info)

No way man, thank you! I'll give it a try! Appreciate your hard work with this, thank you for letting me know, super excited for it!
