### ISSUE TITLE
BUG - uploading using 'open in a new window' feature doesn't work

### ISSUE THREAD

**Issue by nickriebe** [gavvvr/obsidian-imgur-plugin#68]
If you use the 'open in a new window' feature, the plugin fails to work.

Error message: 

If you then close the window, or drag it back to the main obsidian application (as a tab) it works just fine again.

Using:
* Obsidian 1.5.3
* macOS Monterey 12.6.9

**Comment by gavvvr** [comment]
Hi @nickriebe 

Thanks for reporting. Fixed in 2.5.1 (upgrade now)

This was a tricky one. Seems like Obsidian's "new window" is like a separate Chromium engine which has its own copy of types loaded to memory, so the following check failed for clipboard files coming from "new window":

https://github.com/gavvvr/obsidian-imgur-plugin/blob/137c0f112141789d29c1fd9eb3f24ed8ffa0cc42/src/utils/multipart-http.ts#L13C16-L13C39

[Here](https://forum.obsidian.md/t/why-file-in-clipboardevent-is-not-an-instanceof-file-for-notes-opened-in-new-window/76648) is my post on Obsidian forum for reference.
